version: 2.1

jobs:
  one:
    docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub
          password: dockerpassword
    steps:
      - checkout
      - run: echo "A first hello world ~ RS"
      - run: sleep 25

   two:
     docker:
      - image: cimg/ruby:3.0.2
        auth:
          username: mydockerhub
          password: dockerpassword
    steps:
      - run: echo "A second hello world ~ RS"
      - run: sleep 15

workflows:
  version: 2.1
  one_and_two:
    jobs:
      - one
      - two
